# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b3africa', '0002_auto_20180206_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('odk_param_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'b3africa_api_objects',
            },
        ),
        migrations.AlterField(
            model_name='apimethodoptions',
            name='api_method',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='b3africa.APIMethods'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apimethodoptions',
            name='var_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='apiobjects',
            name='api_end_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b3africa.APIEndPoint'),
        ),
        migrations.AddField(
            model_name='apimethodoptions',
            name='api_object',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='b3africa.APIObjects'),
            preserve_default=False,
        ),
    ]
