# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3africa', '0003_auto_20180206_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimethodoptions',
            name='var_default',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
